input {
  # 💡 1. Kafka 대기열에서 실시간으로 데이터를 읽어옵니다.
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["nginx-access-logs"]
    codec => "json" # Filebeat가 JSON으로 보냈으므로 JSON으로 파싱
    group_id => "logstash-security-group"
  }
}

filter {
  # 💡 2. Grok 필터를 사용해 거친 Nginx 문자열 로그를 개별 필드로 쪼갭니다.
  grok {
    match => { "message" => "%{IPORHOST:client_ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{DATA:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:status_code} %{NUMBER:bytes} \"-\" \"%{DATA:user_agent}\"" }
  }

  # 💡 3. 금융권 보안 가이드라인 준수: IP 주소 뒷자리를 'xxx'로 마스킹 처리 (개인정보 보호)
  if [client_ip] {
    mutate {
      gsub => [ "client_ip", "(\d+\.\d+\.\d+)\.\d+", "\1.xxx" ]
    }
  }
}

output {
  # 💡 4. 우선 가공이 잘 되었는지 우리 리눅스 터미널 창에 이쁘게 출력해 봅니다.
  stdout {
    codec => rubydebug
  }

  # 💡 5. 동시에 최종 목적지인 Elasticsearch 분산 저장소로 데이터를 쏩니다.
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-security-logs-%{+YYYY.MM.dd}"
  }
}
