input {
  # 💡 1. Kafka 대기열에서 실시간으로 데이터를 읽어옵니다.
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["nginx-access-logs"]
    codec => "json" # Nginx가 보낸 구조화된 JSON을 다이렉트로 파싱
    group_id => "logstash-security-group"
  }
}

filter {
  # 💡 2. [시나리오 4 최적화] 무거운 Grok 정규식을 배제하고 가벼운 JSON 필터로 괄호만 해제합니다.
  json {
    source => "message"
  }

  # 💡 3. 금융권 보안 가이드라인 준수: 변환된 JSON 필드(remote_addr)의 뒷자리를 'xxx'로 마스킹 처리
  if [remote_addr] {
    mutate {
      gsub => [ "remote_addr", "(\d+\.\d+\.\d+)\.\d+", "\1.xxx" ]
    }
  }
}

output {
  # 💡 4. 가공이 잘 되었는지 리눅스 터미널 창에 실시간으로 출력해 봅니다.
  stdout {
    codec => rubydebug
  }

  # 💡 5. 최종 목적지인 Elasticsearch 분산 저장소로 데이터를 안정적으로 적재합니다.
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-security-logs-%{+YYYY.MM.dd}"
  }
}
